"""Runtime patches for real dashboard detail/order consistency.

The real dashboard overlay is generated by ``real_dashboard_api`` as a dynamic JS
string.  This small patch keeps the large module untouched and adds/fixes:

- holding-day fields in candidate/holding detail panes,
- live-slot candidate fallback for real buy submission,
- order-ticket amount selection so the clicked ticket's input is used,
- front-end success handling after a submitted real buy.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from engine.live import real_dashboard_api as real_api

_INSTALLED = False
_ORIG_SLOT_TO_DASHBOARD = None
_ORIG_ENRICH_POSITION = None
_ORIG_SLOT_OVERLAY_JS = None
_ORIG_CANDIDATE_FOR_REAL = None

_HOLDING_DAY_KEYS = (
    "holding_days",
    "current_holding_days",
    "holding_calendar_days",
    "avg_holding_days",
    "average_holding_days",
    "mean_holding_days",
    "median_holding_days",
    "max_holding_days",
    "rulebook_avg_holding_days",
    "rulebook_median_holding_days",
    "rulebook_max_holding_days",
)


def _usable(value: Any) -> bool:
    return value not in (None, "")


def _copy_holding_day_fields(target: dict[str, Any], *sources: Any) -> dict[str, Any]:
    """Copy holding-day metrics from candidate/rulebook summaries into target."""
    for source in sources:
        if not isinstance(source, dict):
            continue
        for key in _HOLDING_DAY_KEYS:
            value = source.get(key)
            if _usable(value):
                target[key] = value
        summary = source.get("holding_days_summary")
        if isinstance(summary, dict):
            avg = summary.get("avg", summary.get("average", summary.get("mean")))
            median = summary.get("median", summary.get("median_holding_days"))
            mx = summary.get("max", summary.get("max_holding_days"))
            mn = summary.get("min", summary.get("min_holding_days"))
            if _usable(avg):
                target.setdefault("avg_holding_days", avg)
            if _usable(median):
                target.setdefault("median_holding_days", median)
            if _usable(mx):
                target.setdefault("max_holding_days", mx)
            if _usable(mn):
                target.setdefault("min_holding_days", mn)
        metrics = source.get("metrics")
        if isinstance(metrics, dict):
            _copy_holding_day_fields(target, metrics)
        rulebook = source.get("rulebook")
        if isinstance(rulebook, dict):
            _copy_holding_day_fields(target, rulebook)
    return target


def _elapsed_days_from(value: Any) -> float | None:
    if not value:
        return None
    try:
        raw = str(value).strip()
        if not raw:
            return None
        if raw.endswith("Z"):
            raw = raw[:-1] + "+00:00"
        dt = datetime.fromisoformat(raw)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        seconds = (datetime.now(timezone.utc) - dt.astimezone(timezone.utc)).total_seconds()
        return max(0.0, seconds / 86400.0)
    except Exception:
        return None


def _patch_candidate_slot_to_dashboard() -> None:
    global _ORIG_SLOT_TO_DASHBOARD
    if _ORIG_SLOT_TO_DASHBOARD is not None:
        return
    _ORIG_SLOT_TO_DASHBOARD = real_api._candidate_slot_to_dashboard

    def patched_candidate_slot_to_dashboard(slot: dict[str, Any], idx: int) -> dict[str, Any]:
        row = _ORIG_SLOT_TO_DASHBOARD(slot, idx)
        if isinstance(slot, dict) and isinstance(row, dict):
            # real_dashboard_api currently restores max_holding_days and then
            # overwrites it with None later in the same payload.  Put it back and
            # also carry avg/median holding-day fields when upstream provides them.
            _copy_holding_day_fields(row, slot)
        return row

    real_api._candidate_slot_to_dashboard = patched_candidate_slot_to_dashboard


def _patch_candidate_lookup_for_real_buy() -> None:
    """Allow real buy submission for the same live-slot candidates shown on UI.

    /dashboard-real renders candidates from live_slots_state via
    _real_candidate_slots_payload(), while _create_real_buy_intent originally only
    accepted rows from real_dashboard_buy_candidates.json.  When the isolated file
    is empty, a user can see a candidate but order submission fails as stale.  This
    fallback accepts the live-slot row displayed by the real dashboard, while still
    blocking already-held real tickers and non-buyable statuses.
    """
    global _ORIG_CANDIDATE_FOR_REAL
    if _ORIG_CANDIDATE_FOR_REAL is not None:
        return
    _ORIG_CANDIDATE_FOR_REAL = real_api._candidate_for_real

    def patched_candidate_for_real(candidate_id: str) -> dict[str, Any]:
        cid = str(candidate_id or "").strip()
        try:
            return _ORIG_CANDIDATE_FOR_REAL(cid)
        except ValueError as exc:
            if "not found or stale" not in str(exc):
                raise
        state = real_api._live_slots_state()
        row = real_api._find_live_slot_candidate_raw(state, cid)
        if not isinstance(row, dict):
            raise ValueError(f"real candidate not found or stale: {cid}")
        ticker = str(row.get("ticker") or "").upper().strip()
        if not ticker:
            raise ValueError(f"real candidate ticker missing: {cid}")
        held = {
            str(pos.get("ticker") or "").upper().strip()
            for pos in real_api._real_positions_payload()
            if pos.get("ticker") and (real_api._safe_float(pos.get("shares"), 0.0) or 0.0) > 0.0
        }
        if ticker in held:
            raise ValueError(f"real candidate already held: {cid}")
        status = str(row.get("status") or "pending").lower().strip()
        blocked_statuses = {"manual_executed", "auto_executed", "expired", "cancelled", "canceled", "blocked"}
        if status in blocked_statuses:
            raise ValueError(f"real candidate is not pending: {cid}")
        out = dict(row)
        out["candidate_id"] = cid
        out["ticker"] = ticker
        out["status"] = "pending"
        out["manual_buy_enabled"] = True
        out.setdefault("candidate_source", "live_slots_state_fallback")
        out.setdefault("real_candidate_fallback", True)
        return out

    real_api._candidate_for_real = patched_candidate_for_real


def _patch_real_position_enrichment() -> None:
    global _ORIG_ENRICH_POSITION
    if _ORIG_ENRICH_POSITION is not None:
        return
    _ORIG_ENRICH_POSITION = real_api._enrich_real_position_with_candidate_context

    def patched_enrich_real_position_with_candidate_context(row: dict[str, Any]) -> dict[str, Any]:
        out = _ORIG_ENRICH_POSITION(row)
        try:
            ticker = str((out or {}).get("ticker") or (row or {}).get("ticker") or "").upper().strip()
            ctx = real_api._candidate_context_for_real_holding(ticker) if ticker else {}
            if isinstance(out, dict):
                _copy_holding_day_fields(out, ctx)
                if not _usable(out.get("holding_days")):
                    entry_date = out.get("entry_date") or (ctx.get("entry_date") if isinstance(ctx, dict) else None)
                    elapsed = _elapsed_days_from(entry_date)
                    if elapsed is not None:
                        out["holding_days"] = round(elapsed, 2)
                        out["current_holding_days"] = round(elapsed, 2)
        except Exception:
            pass
        return out

    real_api._enrich_real_position_with_candidate_context = patched_enrich_real_position_with_candidate_context


def _patch_slot_overlay_js() -> None:
    global _ORIG_SLOT_OVERLAY_JS
    if _ORIG_SLOT_OVERLAY_JS is not None:
        return
    _ORIG_SLOT_OVERLAY_JS = real_api._real_slot_overlay_js

    helper = r'''
  function firstNum(){
    for(const v of arguments){
      const n=num(v);
      if(n!=null) return n;
    }
    return null;
  }
  function holdingDayFmt(v){
    const n=num(v);
    if(n==null) return '—';
    const body=Math.abs(n-Math.round(n))<0.05 ? String(Math.round(n)) : n.toFixed(1);
    return `${body}일`;
  }
  function inferredHoldingDays(s){
    if(!s) return null;
    const raw=s.entry_date || s.entry_at || s.submitted_at || s.preview_entry_at;
    if(!raw) return null;
    const t=new Date(raw).getTime();
    if(!Number.isFinite(t)) return null;
    return Math.max(0, (Date.now()-t)/86400000);
  }
  function holdingInfoHtml(s, opts={}){
    s=s||{};
    const includeCurrent=opts.includeCurrent!==false;
    const includeEntry=opts.includeEntry!==false;
    const cur=firstNum(s.holding_days, s.current_holding_days, s.holding_calendar_days);
    const inferred=cur==null ? inferredHoldingDays(s) : null;
    const curTxt=cur!=null ? holdingDayFmt(cur) : (inferred!=null ? `${holdingDayFmt(inferred)} <span style="color:var(--dim);font-size:10px;">entry 기준</span>` : '—');
    const max=firstNum(s.max_holding_days, s.rulebook_max_holding_days);
    const avg=firstNum(s.avg_holding_days, s.average_holding_days, s.mean_holding_days, s.rulebook_avg_holding_days);
    const median=firstNum(s.median_holding_days, s.rulebook_median_holding_days);
    const entry=s.entry_date ? `${esc(kstTime(s.entry_date,{mode:'dateTime'}))} KST` : '—';
    let html='';
    if(includeCurrent) html+=`<div class="kv"><span>현재 보유 경과</span><span>${curTxt}</span></div>`;
    html+=`<div class="kv"><span>최대 보유일</span><span>${holdingDayFmt(max)}</span></div>`;
    html+=`<div class="kv"><span>평균 보유일</span><span>${holdingDayFmt(avg)}</span></div>`;
    html+=`<div class="kv"><span>중앙 보유일</span><span>${holdingDayFmt(median)}</span></div>`;
    if(includeEntry) html+=`<div class="kv"><span>진입 기준시각</span><span>${entry}</span></div>`;
    return html;
  }
'''

    def patched_real_slot_overlay_js() -> str:
        js = _ORIG_SLOT_OVERLAY_JS()
        if "function holdingInfoHtml(s, opts={})" not in js:
            js = js.replace(
                "  function tag(v){return v?`<span class=\"tag\">${esc(v)}</span>`:'';}",
                helper + "\n  function tag(v){return v?`<span class=\"tag\">${esc(v)}</span>`:'';}",
            )
            js = js.replace(
                "        <div class=\"kv\"><span>최대 보유</span><span>${esc(s.max_holding_days||'—')}일</span></div>\n        <div class=\"kv\"><span>후보 score</span>",
                "        ${holdingInfoHtml(s)}\n        <div class=\"kv\"><span>후보 score</span>",
            )
            js = js.replace(
                "        <div class=\"kv\"><span>후보 score</span><span style=\"color:var(--up)\">${fmt(s.final_score,3)}</span></div>\n        <div class=\"kv\"><span>백테스트 승률</span>",
                "        ${holdingInfoHtml(s)}\n        <div class=\"kv\"><span>후보 score</span><span style=\"color:var(--up)\">${fmt(s.final_score,3)}</span></div>\n        <div class=\"kv\"><span>백테스트 승률</span>",
            )
            js = js.replace(
                "        <div class=\"kv\"><span>threshold</span><span>${fmt(s.threshold,3)}</span></div>\n        <div class=\"kv\"><span>ratio</span>",
                "        <div class=\"kv\"><span>threshold</span><span>${fmt(s.threshold,3)}</span></div>\n        ${holdingInfoHtml(s,{includeCurrent:false,includeEntry:false})}\n        <div class=\"kv\"><span>ratio</span>",
            )
        # Use the clicked order ticket's amount input first.  The dashboard can
        # render the same candidate in multiple areas, so a global first match can
        # accidentally read the default $100 from another hidden/older ticket.
        js = js.replace(
            "  async function handleBuy(cid, slot){\n"
            "    const s=byCid(cid) || {};\n"
            "    const input=document.getElementById('real-slot-buy-amount') || firstCandidateNode('.slot-buy-amount[data-candidate-id]', cid);\n",
            "  async function handleBuy(cid, slot, trigger){\n"
            "    const s=byCid(cid) || {};\n"
            "    const ticket=trigger && trigger.closest ? trigger.closest('.real-order-ticket') : null;\n"
            "    const input=(ticket && firstCandidateNode('.slot-buy-amount[data-candidate-id]', cid, ticket))\n"
            "      || (document.activeElement && document.activeElement.matches && document.activeElement.matches('.slot-buy-amount[data-candidate-id]') && String(document.activeElement.dataset.candidateId||'')===String(cid||'') ? document.activeElement : null)\n"
            "      || candidateNodes('.slot-buy-amount[data-candidate-id]', cid).find(realIsVisible)\n"
            "      || firstCandidateNode('.slot-buy-amount[data-candidate-id]', cid);\n",
        )
        js = js.replace(
            "      await markSlotBuy(cid, amount, slot);\n"
            "      const mode=(d.intent&&d.intent.execution_mode)||d.execution_mode||'real_intent';",
            "      const d=await markSlotBuy(cid, amount, slot);\n"
            "      const mode=(d.intent&&d.intent.execution_mode)||d.execution_mode||'real_intent';",
        )
        js = js.replace(
            "handleBuy(btn.dataset.candidateId, Number(btn.dataset.slot||0));",
            "handleBuy(btn.dataset.candidateId, Number(btn.dataset.slot||0), btn);",
        )
        return js

    real_api._real_slot_overlay_js = patched_real_slot_overlay_js


def install_real_dashboard_holding_days_patch() -> None:
    """Install real-dashboard runtime patches once per API process."""
    global _INSTALLED
    if _INSTALLED:
        return
    _patch_candidate_slot_to_dashboard()
    _patch_candidate_lookup_for_real_buy()
    _patch_real_position_enrichment()
    _patch_slot_overlay_js()
    _INSTALLED = True
