"""Runtime patches for real dashboard detail/order/chart consistency.

The real dashboard overlay is generated by ``real_dashboard_api`` as a dynamic JS
string.  This small patch keeps the large module untouched and adds/fixes:

- holding-day fields in candidate/holding detail panes,
- live-slot candidate fallback for real buy submission,
- direct real-buy reconciliation wiring for full-rulebook regular candidates,
- order-ticket amount selection so the clicked ticket's input is used,
- front-end success handling after a submitted real buy,
- faster real-dashboard 1m candle refresh cadence.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from engine.live import real_dashboard_api as real_api

_INSTALLED = False
_ORIG_SLOT_TO_DASHBOARD = None
_ORIG_ENRICH_POSITION = None
_ORIG_SLOT_OVERLAY_JS = None
_ORIG_CANDIDATE_FOR_REAL = None
_ORIG_CREATE_REAL_BUY_INTENT = None

_HOLDING_DAY_KEYS = (
    "holding_days",
    "current_holding_days",
    "holding_calendar_days",
    "avg_holding_days",
    "average_holding_days",
    "mean_holding_days",
    "median_holding_days",
    "max_holding_days",
    "rulebook_avg_holding_days",
    "rulebook_median_holding_days",
    "rulebook_max_holding_days",
)


def _usable(value: Any) -> bool:
    return value not in (None, "")


def _copy_holding_day_fields(target: dict[str, Any], *sources: Any) -> dict[str, Any]:
    """Copy holding-day metrics from candidate/rulebook summaries into target."""
    for source in sources:
        if not isinstance(source, dict):
            continue
        for key in _HOLDING_DAY_KEYS:
            value = source.get(key)
            if _usable(value):
                target[key] = value
        summary = source.get("holding_days_summary")
        if isinstance(summary, dict):
            avg = summary.get("avg", summary.get("average", summary.get("mean")))
            median = summary.get("median", summary.get("median_holding_days"))
            mx = summary.get("max", summary.get("max_holding_days"))
            mn = summary.get("min", summary.get("min_holding_days"))
            if _usable(avg):
                target.setdefault("avg_holding_days", avg)
            if _usable(median):
                target.setdefault("median_holding_days", median)
            if _usable(mx):
                target.setdefault("max_holding_days", mx)
            if _usable(mn):
                target.setdefault("min_holding_days", mn)
        metrics = source.get("metrics")
        if isinstance(metrics, dict):
            _copy_holding_day_fields(target, metrics)
        rulebook = source.get("rulebook")
        if isinstance(rulebook, dict):
            _copy_holding_day_fields(target, rulebook)
    return target


def _elapsed_days_from(value: Any) -> float | None:
    if not value:
        return None
    try:
        raw = str(value).strip()
        if not raw:
            return None
        if raw.endswith("Z"):
            raw = raw[:-1] + "+00:00"
        dt = datetime.fromisoformat(raw)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        seconds = (datetime.now(timezone.utc) - dt.astimezone(timezone.utc)).total_seconds()
        return max(0.0, seconds / 86400.0)
    except Exception:
        return None


def _patch_candle_refresh_policy() -> None:
    """Speed up real-dashboard intraday candle refresh without touching live routes."""
    try:
        real_api._REAL_CANDLE_TTL_SEC["1m"] = 10
        real_api._REAL_CANDLE_TTL_SEC["2m"] = 15
        real_api._REAL_CANDLE_TTL_SEC["5m"] = 25
    except Exception:
        pass


def _patch_candidate_slot_to_dashboard() -> None:
    global _ORIG_SLOT_TO_DASHBOARD
    if _ORIG_SLOT_TO_DASHBOARD is not None:
        return
    _ORIG_SLOT_TO_DASHBOARD = real_api._candidate_slot_to_dashboard

    def patched_candidate_slot_to_dashboard(slot: dict[str, Any], idx: int) -> dict[str, Any]:
        row = _ORIG_SLOT_TO_DASHBOARD(slot, idx)
        if isinstance(slot, dict) and isinstance(row, dict):
            # real_dashboard_api currently restores max_holding_days and then
            # overwrites it with None later in the same payload.  Put it back and
            # also carry avg/median holding-day fields when upstream provides them.
            _copy_holding_day_fields(row, slot)
        return row

    real_api._candidate_slot_to_dashboard = patched_candidate_slot_to_dashboard


def _patch_candidate_lookup_for_real_buy() -> None:
    """Allow real buy submission for the same live-slot candidates shown on UI.

    /dashboard-real renders candidates from live_slots_state via
    _real_candidate_slots_payload(), while _create_real_buy_intent originally only
    accepted rows from real_dashboard_buy_candidates.json.  When the isolated file
    is empty, a user can see a candidate but order submission fails as stale.  This
    fallback accepts the live-slot row displayed by the real dashboard, while still
    blocking already-held real tickers and non-buyable statuses.
    """
    global _ORIG_CANDIDATE_FOR_REAL
    if _ORIG_CANDIDATE_FOR_REAL is not None:
        return
    _ORIG_CANDIDATE_FOR_REAL = real_api._candidate_for_real

    def patched_candidate_for_real(candidate_id: str) -> dict[str, Any]:
        cid = str(candidate_id or "").strip()
        try:
            return _ORIG_CANDIDATE_FOR_REAL(cid)
        except ValueError as exc:
            if "not found or stale" not in str(exc):
                raise
        state = real_api._live_slots_state()
        row = real_api._find_live_slot_candidate_raw(state, cid)
        if not isinstance(row, dict):
            raise ValueError(f"real candidate not found or stale: {cid}")
        ticker = str(row.get("ticker") or "").upper().strip()
        if not ticker:
            raise ValueError(f"real candidate ticker missing: {cid}")
        held = {
            str(pos.get("ticker") or "").upper().strip()
            for pos in real_api._real_positions_payload()
            if pos.get("ticker") and (real_api._safe_float(pos.get("shares"), 0.0) or 0.0) > 0.0
        }
        if ticker in held:
            raise ValueError(f"real candidate already held: {cid}")
        status = str(row.get("status") or "pending").lower().strip()
        blocked_statuses = {"manual_executed", "auto_executed", "expired", "cancelled", "canceled", "blocked"}
        if status in blocked_statuses:
            raise ValueError(f"real candidate is not pending: {cid}")
        out = dict(row)
        out["candidate_id"] = cid
        out["ticker"] = ticker
        out["status"] = "pending"
        out["manual_buy_enabled"] = True
        out.setdefault("candidate_source", "live_slots_state_fallback")
        out.setdefault("real_candidate_fallback", True)
        return out

    real_api._candidate_for_real = patched_candidate_for_real


def _order_status_value(order: Any) -> str:
    value = getattr(order, "status", "")
    value = getattr(value, "value", value)
    return str(value or "").strip().lower()


def _is_fallback_candidate(candidate: dict[str, Any]) -> bool:
    return bool(candidate.get("real_candidate_fallback")) or str(candidate.get("candidate_source") or "") == "live_slots_state_fallback"


def _entry_market_context_from_candidate(candidate: dict[str, Any], selected_rulebook: dict[str, Any]) -> dict[str, Any]:
    return {
        "market_score": real_api._safe_float(candidate.get("market_score"), None),
        "vix_level": real_api._safe_float(candidate.get("vix_level"), None),
        "sector_score": real_api._safe_float(candidate.get("sector_score"), None),
        "sector_name": str(selected_rulebook.get("sector_name") or candidate.get("sector_name") or ""),
        "source": "dashboard_real_candidate_snapshot",
        "candidate_id": str(candidate.get("candidate_id") or ""),
        "rulebook_hash": str(candidate.get("selected_rulebook_hash") or candidate.get("rulebook_hash") or ""),
    }


def _full_rulebook_dict(candidate: dict[str, Any]) -> dict[str, Any] | None:
    selected = candidate.get("selected_rulebook")
    if not isinstance(selected, dict) or not selected:
        return None
    return dict(selected)


def _selected_rulebook_hash(candidate: dict[str, Any], selected_rulebook: dict[str, Any]) -> str:
    value = str(candidate.get("selected_rulebook_hash") or candidate.get("rulebook_hash") or "").strip()
    if value:
        return value
    try:
        from engine.core.metadata import compute_member_hash

        return compute_member_hash(dict(selected_rulebook))
    except Exception:
        return ""


def _real_buy_preflight_metadata(candidate: dict[str, Any]) -> tuple[dict[str, Any] | None, str]:
    selected_rulebook = _full_rulebook_dict(candidate)
    if selected_rulebook is None:
        return None, "REJECTED: regular candidate has no valid selected_rulebook — order blocked for exit safety"
    atr = real_api._safe_float(candidate.get("preflight_atr") or candidate.get("atr"), 0.0) or 0.0
    if atr <= 0.0:
        return None, "REJECTED: regular candidate has no valid ATR — order blocked for exit safety"
    try:
        from engine.strategies.rulebook import Rulebook

        Rulebook.from_dict(dict(selected_rulebook))
    except Exception as exc:
        return None, f"REJECTED: regular candidate selected_rulebook cannot be restored — order blocked for exit safety: {type(exc).__name__}: {exc}"
    selected_hash = _selected_rulebook_hash(candidate, selected_rulebook)
    metadata = {
        "selected_rulebook": dict(selected_rulebook),
        "selected_rulebook_hash": selected_hash,
        "rulebook": dict(selected_rulebook),
        "preflight_atr": float(atr),
        "atr": float(atr),
        "entry_market_context": _entry_market_context_from_candidate(candidate, selected_rulebook),
        "candidate_id": str(candidate.get("candidate_id") or ""),
        "ticker": str(candidate.get("ticker") or "").upper().strip(),
        "candidate_source": str(candidate.get("candidate_source") or ""),
        "real_candidate_fallback": bool(candidate.get("real_candidate_fallback")),
        "source_file": str(candidate.get("source_file") or ""),
        "rulebook_hash": str(candidate.get("rulebook_hash") or selected_hash),
        "reason": "dashboard_real_direct_entry",
    }
    return metadata, ""


def _reject_real_buy_intent(
    *,
    row: dict[str, Any],
    intents: dict[str, Any],
    data: dict[str, Any],
    intent_id: str,
    candidate_id: str,
    ticker: str,
    candidate: dict[str, Any],
    reason: str,
    execution_mode: str,
) -> dict[str, Any]:
    row.update(
        {
            "status": "rejected",
            "rejected_at": real_api.utc_now_iso(),
            "rejection_reason": reason,
            "execution_mode": execution_mode,
            "order_blocked": True,
            "broker_order": None,
            "position_registered": False,
            "pending_order_tracked": False,
            "reconciliation_status": "blocked_before_order",
        }
    )
    real_api._append_live_slot_event(
        {
            "event": "DASHBOARD_REAL_BUY_REJECTED",
            "time": row.get("rejected_at"),
            "candidate_id": candidate_id,
            "ticker": ticker,
            "source": row.get("source"),
            "execution_mode": row.get("execution_mode"),
            "status": row.get("status"),
            "reason": reason,
            "candidate_source": candidate.get("candidate_source"),
            "real_candidate_fallback": bool(candidate.get("real_candidate_fallback")),
        }
    )
    intents[intent_id] = row
    real_api._write_intent_state(real_api.REAL_BUY_INTENT_PATH, data)
    return row


def _position_snapshot_for_row(position: Any) -> dict[str, Any]:
    if position is None:
        return {}
    return {
        "position_ticker": getattr(position, "ticker", ""),
        "position_entry_price": getattr(position, "entry_price", None),
        "position_shares": getattr(position, "shares", None),
        "position_member_hash": getattr(position, "member_hash", ""),
        "position_stop_price": getattr(position, "stop_price", None),
        "position_target_price": getattr(position, "target_price", None),
        "position_trailing_stop": getattr(position, "trailing_stop", None),
        "position_trailing_distance": getattr(position, "trailing_distance", None),
        "position_max_holding_days": getattr(position, "max_holding_days", None),
        "position_exit_strategy": getattr(position, "exit_strategy", ""),
        "position_rulebook_snapshot_len": len(getattr(position, "rulebook_snapshot", {}) or {}),
    }


def _wire_real_buy_reconciliation(
    *,
    broker: Any,
    order: Any,
    candidate: dict[str, Any],
    metadata: dict[str, Any],
    row: dict[str, Any],
) -> dict[str, Any]:
    status = _order_status_value(order)
    if status == "filled":
        from engine.live.buy_reconciliation import BuyPreflight, BuyReconciliationService
        from engine.live.position_manager import PositionManager
        from engine.strategies.rulebook import Rulebook

        position_manager = PositionManager()
        ticker = str(candidate.get("ticker") or getattr(order, "ticker", "") or "").upper().strip()
        existing = position_manager.get(ticker) if hasattr(position_manager, "get") else None
        rulebook = Rulebook.from_dict(dict(metadata["selected_rulebook"]))
        preflight = BuyPreflight(
            atr=float(metadata["preflight_atr"]),
            rulebook=rulebook,
            entry_market_context=dict(metadata.get("entry_market_context") or {}),
        )
        service = BuyReconciliationService(
            broker=broker,
            rulebook_provider=None,
            position_manager=position_manager,
            pending_manager=None,
        )
        position = service.reconcile(order, purpose="entry", preflight=preflight)
        existing_returned = existing is not None and position is existing
        row.update(
            {
                "position_registered": bool(position is not None and not existing_returned),
                "existing_position_returned": bool(existing_returned),
                "pending_order_tracked": False,
                "reconciliation_status": "existing_position_returned" if existing_returned else "registered",
                "reconciliation_at": real_api.utc_now_iso(),
            }
        )
        row.update(_position_snapshot_for_row(position))
        return row

    if status in {"pending", "partial", "submitted", "accepted", "new", "pending_new"}:
        from engine.live.pending_order_manager import PendingOrderManager

        pending_manager = PendingOrderManager(broker)
        record = pending_manager.track_order(order, purpose="entry", metadata=dict(metadata))
        row.update(
            {
                "position_registered": False,
                "pending_order_tracked": record is not None,
                "pending_order_tracked_at": real_api.utc_now_iso(),
                "pending_order_id": getattr(record, "order_id", "") if record is not None else "",
                "pending_order_client_order_id": getattr(record, "client_order_id", "") if record is not None else "",
                "pending_order_state": getattr(record, "state", "") if record is not None else "",
                "reconciliation_deferred": True,
                "reconciliation_status": "pending_order_tracked" if record is not None else "pending_order_not_tracked",
            }
        )
        return row

    row.update(
        {
            "position_registered": False,
            "pending_order_tracked": False,
            "reconciliation_status": f"terminal_no_fill:{status or 'unknown'}",
            "reconciliation_deferred": False,
        }
    )
    return row


def _patch_direct_buy_reconciliation_wiring() -> None:
    """Wire regular full-rulebook dashboard-real buys to entry reconciliation.

    This intentionally leaves the SAFETY fallback guard in front of the broker call.
    Fallback/compact candidates are rejected before this reconciliation plumbing can
    run.  Regular candidates must carry selected_rulebook and positive ATR before
    a live order is allowed, preventing orphan buys without exit metadata.
    """
    global _ORIG_CREATE_REAL_BUY_INTENT
    if _ORIG_CREATE_REAL_BUY_INTENT is not None:
        return
    _ORIG_CREATE_REAL_BUY_INTENT = real_api._create_real_buy_intent

    def patched_create_real_buy_intent(req: Any) -> dict[str, Any]:
        candidate = real_api._candidate_for_real(req.candidate_id)
        candidate_id = str(req.candidate_id or "").strip()
        ticker = str(candidate.get("ticker") or "").upper().strip()
        if not ticker:
            raise ValueError("real candidate ticker missing")
        default_notional = real_api._safe_float(candidate.get("notional"), 0.0) or 0.0
        notional = real_api._positive_float(req.notional if req.notional is not None else default_notional, name="notional")
        trade_date = str(candidate.get("trade_date") or candidate.get("execution_session") or "")
        data = real_api._intent_state(real_api.REAL_BUY_INTENT_PATH, default_trade_date=trade_date)
        intents = data.setdefault("intents", {})
        now = real_api.utc_now_iso()
        intent_id = f"real-buy:{candidate_id}"
        row = dict(intents.get(intent_id) or {})
        row.update(
            {
                "intent_id": intent_id,
                "candidate_id": candidate_id,
                "trade_date": trade_date,
                "status": "pending",
                "source": req.source or "real_dashboard",
                "ticker": ticker,
                "entity_id": candidate.get("entity_id"),
                "notional": notional,
                "candidate_notional": default_notional,
                "price": real_api._safe_float(candidate.get("price"), 0.0) or 0.0,
                "created_at": row.get("created_at") or now,
                "updated_at": now,
                "execution_mode": "real_intent_only",
                "direct_orders_enabled": real_api._direct_orders_enabled(),
                "candidate_state_path": str(real_api.REAL_BUY_CANDIDATES_PATH),
                "candidate_snapshot": candidate,
                "connection": real_api._public_connection_config(),
                "note": "real dashboard isolated candidate/intents; no paper/live state touched",
            }
        )
        if real_api._direct_orders_enabled():
            if _is_fallback_candidate(candidate):
                return _reject_real_buy_intent(
                    row=row,
                    intents=intents,
                    data=data,
                    intent_id=intent_id,
                    candidate_id=candidate_id,
                    ticker=ticker,
                    candidate=candidate,
                    reason="REJECTED: fallback candidate has no verified full rulebook — order blocked for safety",
                    execution_mode="blocked_fallback_candidate_no_verified_full_rulebook",
                )
            metadata, rejection_reason = _real_buy_preflight_metadata(candidate)
            if metadata is None:
                return _reject_real_buy_intent(
                    row=row,
                    intents=intents,
                    data=data,
                    intent_id=intent_id,
                    candidate_id=candidate_id,
                    ticker=ticker,
                    candidate=candidate,
                    reason=rejection_reason,
                    execution_mode="blocked_regular_candidate_missing_exit_metadata",
                )
            row["entry_preflight_metadata"] = metadata
            broker = real_api._get_real_broker()
            if broker is None:
                raise ValueError(f"real broker unavailable: {real_api._real_broker_error}")
            price = real_api._safe_float(broker.get_current_price(ticker)) or real_api._safe_float(candidate.get("price"))
            if price is None or price <= 0.0:
                raise ValueError(f"current price unavailable for {ticker}")
            shares = notional / price
            order = broker.place_buy(ticker, shares, order_type=real_api.OrderType.MARKET, price=0.0, client_order_id=f"km-real-buy-{int(real_api.time.time())}-{ticker}")
            row.update(
                {
                    "status": "submitted",
                    "submitted_at": real_api.utc_now_iso(),
                    "shares_requested": shares,
                    "execution_mode": "direct_alpaca_live_market_order",
                    "broker_order": real_api._order_dict(order),
                }
            )
            try:
                _wire_real_buy_reconciliation(broker=broker, order=order, candidate=candidate, metadata=metadata, row=row)
            except Exception as exc:
                row.update(
                    {
                        "position_registered": False,
                        "pending_order_tracked": False,
                        "reconciliation_status": "failed",
                        "reconciliation_error": f"{type(exc).__name__}: {exc}",
                    }
                )
                real_api._append_live_slot_event(
                    {
                        "event": "DASHBOARD_REAL_BUY_RECONCILIATION_FAILED",
                        "time": real_api.utc_now_iso(),
                        "candidate_id": candidate_id,
                        "ticker": ticker,
                        "status": row.get("status"),
                        "execution_mode": row.get("execution_mode"),
                        "reason": row.get("reconciliation_error"),
                    }
                )
        intents[intent_id] = row
        real_api._write_intent_state(real_api.REAL_BUY_INTENT_PATH, data)
        return row

    real_api._create_real_buy_intent = patched_create_real_buy_intent


def _patch_real_position_enrichment() -> None:
    global _ORIG_ENRICH_POSITION
    if _ORIG_ENRICH_POSITION is not None:
        return
    _ORIG_ENRICH_POSITION = real_api._enrich_real_position_with_candidate_context

    def patched_enrich_real_position_with_candidate_context(row: dict[str, Any]) -> dict[str, Any]:
        out = _ORIG_ENRICH_POSITION(row)
        try:
            ticker = str((out or {}).get("ticker") or (row or {}).get("ticker") or "").upper().strip()
            ctx = real_api._candidate_context_for_real_holding(ticker) if ticker else {}
            if isinstance(out, dict):
                _copy_holding_day_fields(out, ctx)
                if not _usable(out.get("holding_days")):
                    entry_date = out.get("entry_date") or (ctx.get("entry_date") if isinstance(ctx, dict) else None)
                    elapsed = _elapsed_days_from(entry_date)
                    if elapsed is not None:
                        out["holding_days"] = round(elapsed, 2)
                        out["current_holding_days"] = round(elapsed, 2)
        except Exception:
            pass
        return out

    real_api._enrich_real_position_with_candidate_context = patched_enrich_real_position_with_candidate_context


def _patch_slot_overlay_js() -> None:
    global _ORIG_SLOT_OVERLAY_JS
    if _ORIG_SLOT_OVERLAY_JS is not None:
        return
    _ORIG_SLOT_OVERLAY_JS = real_api._real_slot_overlay_js

    helper = r'''
  function firstNum(){
    for(const v of arguments){
      const n=num(v);
      if(n!=null) return n;
    }
    return null;
  }
  function holdingDayFmt(v){
    const n=num(v);
    if(n==null) return '—';
    const body=Math.abs(n-Math.round(n))<0.05 ? String(Math.round(n)) : n.toFixed(1);
    return `${body}일`;
  }
  function inferredHoldingDays(s){
    if(!s) return null;
    const raw=s.entry_date || s.entry_at || s.submitted_at || s.preview_entry_at;
    if(!raw) return null;
    const t=new Date(raw).getTime();
    if(!Number.isFinite(t)) return null;
    return Math.max(0, (Date.now()-t)/86400000);
  }
  function holdingInfoHtml(s, opts={}){
    s=s||{};
    const includeCurrent=opts.includeCurrent!==false;
    const includeEntry=opts.includeEntry!==false;
    const cur=firstNum(s.holding_days, s.current_holding_days, s.holding_calendar_days);
    const inferred=cur==null ? inferredHoldingDays(s) : null;
    const curTxt=cur!=null ? holdingDayFmt(cur) : (inferred!=null ? `${holdingDayFmt(inferred)} <span style="color:var(--dim);font-size:10px;">entry 기준</span>` : '—');
    const max=firstNum(s.max_holding_days, s.rulebook_max_holding_days);
    const avg=firstNum(s.avg_holding_days, s.average_holding_days, s.mean_holding_days, s.rulebook_avg_holding_days);
    const median=firstNum(s.median_holding_days, s.rulebook_median_holding_days);
    const entry=s.entry_date ? `${esc(kstTime(s.entry_date,{mode:'dateTime'}))} KST` : '—';
    let html='';
    if(includeCurrent) html+=`<div class="kv"><span>현재 보유 경과</span><span>${curTxt}</span></div>`;
    html+=`<div class="kv"><span>최대 보유일</span><span>${holdingDayFmt(max)}</span></div>`;
    html+=`<div class="kv"><span>평균 보유일</span><span>${holdingDayFmt(avg)}</span></div>`;
    html+=`<div class="kv"><span>중앙 보유일</span><span>${holdingDayFmt(median)}</span></div>`;
    if(includeEntry) html+=`<div class="kv"><span>진입 기준시각</span><span>${entry}</span></div>`;
    return html;
  }
'''

    active_detail_refresh = r'''
  async function refreshActiveRealDetailChart(){
    try{
      const detail=document.getElementById('slot-detail-view');
      if(!detail || detail.style.display==='none') return;
      const ac=(typeof _activeChart!=='undefined') ? _activeChart : null;
      if(!ac || !['real_candidate','preview_holding','real_holding'].includes(String(ac.type||''))) return;
      const ticker=String(ac.ticker||'').toUpperCase();
      const interval=String(ac.interval||'1m');
      if(!ticker || interval!=='1m') return;
      if(typeof window.drawChart==='function') await window.drawChart(ticker, interval);
      if(String(ac.type||'')==='real_candidate' && typeof applyRealCandidateDetailSignal==='function') await applyRealCandidateDetailSignal(ticker, interval);
      updateRealUpdateBadge({chartFetch:new Date().toISOString()});
    }catch(e){}
  }
'''

    def patched_real_slot_overlay_js() -> str:
        js = _ORIG_SLOT_OVERLAY_JS()
        if "function holdingInfoHtml(s, opts={})" not in js:
            js = js.replace(
                "  function tag(v){return v?`<span class=\"tag\">${esc(v)}</span>`:'';}",
                helper + "\n  function tag(v){return v?`<span class=\"tag\">${esc(v)}</span>`:'';}",
            )
            js = js.replace(
                "        <div class=\"kv\"><span>최대 보유</span><span>${esc(s.max_holding_days||'—')}일</span></div>\n        <div class=\"kv\"><span>후보 score</span>",
                "        ${holdingInfoHtml(s)}\n        <div class=\"kv\"><span>후보 score</span>",
            )
            js = js.replace(
                "        <div class=\"kv\"><span>후보 score</span><span style=\"color:var(--up)\">${fmt(s.final_score,3)}</span></div>\n        <div class=\"kv\"><span>백테스트 승률</span>",
                "        ${holdingInfoHtml(s)}\n        <div class=\"kv\"><span>후보 score</span><span style=\"color:var(--up)\">${fmt(s.final_score,3)}</span></div>\n        <div class=\"kv\"><span>백테스트 승률</span>",
            )
            js = js.replace(
                "        <div class=\"kv\"><span>threshold</span><span>${fmt(s.threshold,3)}</span></div>\n        <div class=\"kv\"><span>ratio</span>",
                "        <div class=\"kv\"><span>threshold</span><span>${fmt(s.threshold,3)}</span></div>\n        ${holdingInfoHtml(s,{includeCurrent:false,includeEntry:false})}\n        <div class=\"kv\"><span>ratio</span>",
            )
        # Use the clicked order ticket's amount input first.  The dashboard can
        # render the same candidate in multiple areas, so a global first match can
        # accidentally read the default $100 from another hidden/older ticket.
        js = js.replace(
            "  async function handleBuy(cid, slot){\n"
            "    const s=byCid(cid) || {};\n"
            "    const input=document.getElementById('real-slot-buy-amount') || firstCandidateNode('.slot-buy-amount[data-candidate-id]', cid);\n",
            "  async function handleBuy(cid, slot, trigger){\n"
            "    const s=byCid(cid) || {};\n"
            "    const ticket=trigger && trigger.closest ? trigger.closest('.real-order-ticket') : null;\n"
            "    const input=(ticket && firstCandidateNode('.slot-buy-amount[data-candidate-id]', cid, ticket))\n"
            "      || (document.activeElement && document.activeElement.matches && document.activeElement.matches('.slot-buy-amount[data-candidate-id]') && String(document.activeElement.dataset.candidateId||'')===String(cid||'') ? document.activeElement : null)\n"
            "      || candidateNodes('.slot-buy-amount[data-candidate-id]', cid).find(realIsVisible)\n"
            "      || firstCandidateNode('.slot-buy-amount[data-candidate-id]', cid);\n",
        )
        js = js.replace(
            "      await markSlotBuy(cid, amount, slot);\n"
            "      const mode=(d.intent&&d.intent.execution_mode)||d.execution_mode||'real_intent';",
            "      const d=await markSlotBuy(cid, amount, slot);\n"
            "      const mode=(d.intent&&d.intent.execution_mode)||d.execution_mode||'real_intent';",
        )
        js = js.replace(
            "handleBuy(btn.dataset.candidateId, Number(btn.dataset.slot||0));",
            "handleBuy(btn.dataset.candidateId, Number(btn.dataset.slot||0), btn);",
        )
        # Faster real-candidate 1m chart refresh.  Underlying data may still be
        # sparse for illiquid tickers, but the browser/server cache should no
        # longer add 30-45 seconds of avoidable delay.
        js = js.replace("KST · 서버 TTL 25초", "KST · 서버 TTL 10초")
        js = js.replace("const ttlMs=45000;", "const ttlMs=10000;")
        js = js.replace(
            "  if(!chartLibReady()) setTimeout(()=>{ if(!chartLibReady()) markChartLibWaiting(document); }, 3500);",
            active_detail_refresh + "\n  if(!chartLibReady()) setTimeout(()=>{ if(!chartLibReady()) markChartLibWaiting(document); }, 3500);",
        )
        js = js.replace(
            "if(!window._realCandidateSlotsInterval) window._realCandidateSlotsInterval=setInterval(loadCandidateSlots, 30000);",
            "if(!window._realCandidateSlotsInterval) window._realCandidateSlotsInterval=setInterval(loadCandidateSlots, 15000);",
        )
        js = js.replace(
            "if(!window._realCandidateChartInterval) window._realCandidateChartInterval=setInterval(()=>scheduleCandidateMiniChartDraw(false, 0), 30000);",
            "if(!window._realCandidateChartInterval) window._realCandidateChartInterval=setInterval(()=>scheduleCandidateMiniChartDraw(false, 0), 10000);\n  if(!window._realActiveDetailChartInterval) window._realActiveDetailChartInterval=setInterval(refreshActiveRealDetailChart, 10000);",
        )
        return js

    real_api._real_slot_overlay_js = patched_real_slot_overlay_js


def install_real_dashboard_holding_days_patch() -> None:
    """Install real-dashboard runtime patches once per API process."""
    global _INSTALLED
    if _INSTALLED:
        return
    _patch_candle_refresh_policy()
    _patch_candidate_slot_to_dashboard()
    _patch_candidate_lookup_for_real_buy()
    _patch_direct_buy_reconciliation_wiring()
    _patch_real_position_enrichment()
    _patch_slot_overlay_js()
    _INSTALLED = True
